[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  CI = "true"

# SPA redirect: envia qualquer rota para o index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200